spring:
  datasource:
    url: jdbc:mysql://localhost:3306/basquiat?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: root
    password: '@1234qwer'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: 'select 1'
      connection-timeout: 10000
      maximum-pool-size: 10
      pool-name: basquiat-pool
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        use_sql_comments: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    allow-bean-definition-overriding: true

# loggin level setting
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace